import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    'intro',
    {type: 'autogenerated', dirName: 'getting-started'},
  ],
  componentsSidebar: [{type: 'autogenerated', dirName: 'components'}],
  guidesSidebar: [
    {type: 'autogenerated', dirName: 'best-practices'},
    {type: 'autogenerated', dirName: 'reference'},
  ],
  contributorSidebar: [
    {type: 'autogenerated', dirName: 'contributing'},
    {type: 'autogenerated', dirName: 'platform'},
  ],
};

export default sidebars;
