import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import productRegistry from './config/products.json';

const productSidebars = Object.fromEntries(
  productRegistry.products
    .filter((product) => product.id !== 'cli' && product.id !== 'desktop')
    .map((product) => [
      `product-${product.id}`,
      [{type: 'autogenerated' as const, dirName: `products/${product.id}`}],
    ]),
);

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    'intro',
    {type: 'autogenerated', dirName: 'getting-started'},
  ],
  productOverviewSidebar: ['products/index'],
  'product-cli': [
    {
      type: 'category',
      label: 'Get Started',
      collapsible: true,
      collapsed: false,
      items: [
        'products/cli/quickstart',
        'products/cli/installation',
        'products/cli/agent-skill',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: true,
      collapsed: false,
      items: [
        'products/cli/command-reference',
        'products/cli/guides',
        'products/cli/reference',
        'products/cli/release-notes',
      ],
    },
    {
      type: 'category',
      label: 'Integrate',
      collapsible: true,
      collapsed: false,
      items: ['products/cli/ecosystem'],
    },
  ],
  'product-desktop': [
    {
      type: 'category',
      label: 'MaxCompute AI数据探索',
      link: {type: 'doc', id: 'products/desktop/index'},
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: '入门',
          collapsible: true,
          collapsed: false,
          items: [
            'products/desktop/quickstart',
            'products/desktop/installation',
          ],
        },
        {
          type: 'category',
          label: '数据工作台',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'category',
              label: '数据源',
              collapsible: true,
              collapsed: false,
              items: [
                'products/desktop/connection',
                'products/desktop/multi-datasource',
                'products/desktop/oss-files',
              ],
            },
            'products/desktop/catalog-insights',
            'products/desktop/sql-analysis',
            'products/desktop/dashboard',
            'products/desktop/maxframe-notebook',
            'products/desktop/python-udf',
            'products/desktop/data-import',
          ],
        },
        {
          type: 'category',
          label: 'DataAgent',
          collapsible: true,
          collapsed: false,
          items: [
            'products/desktop/ai-query',
            'products/desktop/expert-mode',
            'products/desktop/semantic-pack',
          ],
        },
        {
          type: 'category',
          label: '多模态',
          collapsible: true,
          collapsed: false,
          items: [
            'products/desktop/multimodal-blob',
            'products/desktop/aigc-studio',
          ],
        },
        {
          type: 'category',
          label: '扩展生态',
          collapsible: true,
          collapsed: false,
          items: [
            'products/desktop/ecosystem',
            'products/desktop/dbt-integration',
            'products/desktop/office-collaboration',
          ],
        },
        {
          type: 'category',
          label: '参考',
          collapsible: true,
          collapsed: false,
          items: [
            'products/desktop/reference',
            'products/desktop/release-notes',
            'products/desktop/troubleshooting',
          ],
        },
      ],
    },
  ],
  ...productSidebars,
  resourcesSidebar: [
    {type: 'autogenerated', dirName: 'best-practices'},
    {type: 'autogenerated', dirName: 'updates'},
    {type: 'autogenerated', dirName: 'faq'},
    {type: 'autogenerated', dirName: 'reference'},
  ],
};

export default sidebars;
