import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

import productRegistry from './config/products.json';

const productSidebars = Object.fromEntries(
  productRegistry.products.map((product) => [
    `product-${product.id}`,
    [{type: 'autogenerated' as const, dirName: `products/${product.id}`}],
  ]),
);

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    'intro',
    {type: 'autogenerated', dirName: 'getting-started'},
  ],
  productOverviewSidebar: ['products/index'],
  ...productSidebars,
  resourcesSidebar: [
    {type: 'autogenerated', dirName: 'best-practices'},
    {type: 'autogenerated', dirName: 'updates'},
    {type: 'autogenerated', dirName: 'faq'},
    {type: 'autogenerated', dirName: 'reference'},
  ],
};

export default sidebars;
